### PR TITLE
Changes on es locale

### PR DESCRIPTION
**Pull request by mcmtradu**
- Reviewed previously translated strings 
- Improved readability
- Translated new strings

### CODE REVIEW

**Comment by mcmtradu** [comment]
Hi @schmich,
I've realised that there's a mistake in one of the strings, could you please not accept this pull request until I have amended it? I'll let you know when done. Thanks!

**Comment by schmich** [comment]
Hi @mcmtradu. You've created a pull request for your own fork. You need to create a pull request against my fork in order for me to incorporate it.

You can [create the pull request against my fork here](https://github.com/schmich/marinara/pulls) by clicking the "New Pull Request" button. Let me know if you have any issues.

**Comment by mcmtradu** [comment]
Hi @schmich,

So sorry about that, I'm still new at this. I will make the changes to the strings and create a pull request against your fork later.

**Comment by schmich** [comment]
No problem at all. This stuff can be complex and annoying at times, but stick with it and it'll start to make sense.

I appreciate the perseverance and your willingness to contribute!

**Pull request closed without merging**
